### ISSUE TITLE
Add fix for RelationBroken fired when relation isn't breaking

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-router-k8s-operator#103]
https://bugs.launchpad.net/juju/+bug/1979811

RelationBroken fired on departing unit when relation isn't breaking. If unit is leader unit, it will delete database_provides databags when it shouldn't

**Comment by taurus-forever** [comment]
@carlcsaposs-canonical I have escalated the the bugreport. Fingerscrossed.
Meanwhile, here is the previos workaround implementation: https://github.com/canonical/mysql-operator/pull/40
