### ISSUE TITLE
update-status lag before presentation of connection information to consuming application

### ISSUE THREAD

**Issue by javacruft** [canonical/mysql-router-k8s-operator#12]
### Bug Description

While debugging #11 I noticed that there is a short lag between the mysql-k8s clustered service starting up and then the consuming application on the other side of mysql-router-k8s actually receiving connection information for the database.

I'm guessing that this latter event is triggered as a side effect of an update-status hook execution when a deferred event is then executed to catch everything up - this could be improved some some notifications on the relation between mysql-k8s and mysql-router-k8s avoiding a potential 5 minute lag during deployment.

### To Reproduce

See #11 

### Environment

microk8s (1.25-strict/stable)

### Relevant log output

```shell
See #11
```

**Comment by taurus-forever** [comment]
Dear @javacruft , the reported issue should be fixed as a part of [PR#25](https://github.com/canonical/mysql-router-k8s-operator/pull/25). mysql-router-k8s revision 8+ should work like a charm for you. :-D
Please check it from your side and reopen if necessary.
