### ISSUE TITLE
Set `BlockedStatus` if unsupported extra user role requested

### ISSUE THREAD

**Issue by carlcsaposs-canonical** [canonical/mysql-router-k8s-operator#61]
> what should UX be if a user requests `extra_user_roles`, which are not supported by this code?

_Originally posted by @delgod in https://github.com/canonical/mysql-router-k8s-operator/pull/51#discussion_r1191136666_

**Comment by delgod** [comment]
> @delgod If two applications are related to mysql-router-k8s and one of them does not request extra user roles (correct) and one of them requests an unsupported extra user role (incorrect), should mysql-router-k8s enter BlockedStatus?

Yes - status should be Blocked. Charm should continue to work correctly even if the status is blocked.
